language: node_js
node_js:
  - "node"
script:
  -
branches:
  only:
    - master
deploy:
  provider: firebase
  token:
    secure: "iu1Qsc62tL2wC8/Wnp58EuSRKQnrW35B+bMp7yYhbHvN/rAjzlcHLkEs9Chp+ry5GbpwaV1qzB5F4u2aYGBg4rtAUDk6w9bhK8wQbWjfTcazqsOxg7Q0IxM0tm7Vrdo498GcdZUKbDniJ13LcJOXBqKDawpbkVZ7n3vsk2cO7UV9GIvawcSnHI7TTTO1/TpxGeHMxRga/12eO3UIN6e7Fut20VxKUG9ydXtE+Ff8r9wAlcQvL1EcQctoOt30u/u0nKvOUYeZ2nfLJGaqp0L/7FsteXcSWeZxH8iIfgZ2jOoj76E7vw0DT3jwRJE/pG1wMzpjeUjIMhZHEF8JDtbq/+Hg6ZfTQ/WIb3PA3zcaf1XiVBcEbbbVhMyFRuMR01ntcKkJgAddqh7WcAb6ozkNgUU3Z0rEtvlkB9JRe1bKQyQ3gQ5ePdNxAKPYSt8KgGiE6xe5kSxhlKe/NVoPVCzfWLhCEEMA2vVG7whs7JADmU0ibdZCjkwkscWvyjdoBYmwoTgnYifTPDqAN3ocDMlApSkHcBHBPZPuj1RxUWCu0NmDXEevvWspU7l6RfBDYgEw5Dk7M3gKEkYmHDHwPurKEXdbuJfF+NU5VaJeJ4bV/tG6MLS9C1W6TzxiCpUifnCpVbMwJbh0jjqW45/85bJPqgKMIKufUzrg4iWl/Nf+ofg="
