language: node_js
node_js:
  - node
script:
  -
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: AKIAIJUAZCC2KA7PPCMQ
  secret_access_key:
    secure: W4y7UI08fIks0dYYIs0oiIUrhj8yJFDKSOIf/yjuv583AHKV1sRty2uOsrNjBeE6mYEIMT2pZJrnF36XjjGg4YOYxBzmINN+VKMFmyW0yQ6qotc/vf12L4wXQ6X8deOQT6XM59DNCYD7ccAEw3uoDXcFn4gBLUEqrJU6ikuHch957EqpJe8kumar3a6QBnmV37nyzbCk4K4qM4XB/1QTr1APTLP5WHpDSmihUJCuYRoJieGQdnjukFeIuPcGw7MZQADB8vdf3KEUoMkaRKaG3CzEUkte4OAi8EM3I6Mxx9ArMEnwOywwrysYQfJsOLHf6AfwretzZNzC0A1QbMjzoHCviBkePLHwuHVy2uCLcMAhqAASUdZctlbRVh4zvzS3F9WmDF1lG/6yhSWTXhnQapOwJPHOub4CKfuishzCNx3QkVKHqshaOYXrtE6M0jc4nFkwiKHxWzSI8HWGm6Fcovo32QbT3QpYn5CqJwnyIjAdyRLn9AEwwX+EIxP3jct7bWF1zb0AR+r5Brg6qSQv/KTlU60henmBnDbwhostqwNAPhItrJvlXXqAR0amGEp0Ha2prTQ4KOBrdEwDBk3yHFdZkI0+n9gaEFRv8To50eQZ9NIF6wdt8s++F3TQ2mgVqasjz9eKnA/9fCgjqUArbQgEIYh/drL+sCwd0mXvxsk=
  bucket: rooftop.city
